Cargo.lock, Cargo.toml
These are used by the serde example, but where not included in the Cargo.toml
=> Add serde crates for toml example

src/basics.md
Following examples were added:
- Generate random floating point numbers
- Generate random values of a custom type
resolves https://github.com/brson/rust-cookbook/issues/50
Unfortunately due to https://github.com/rust-lang-nursery/rand/issues/146 i see no way for the `Generate random values of a custom type` to use SampleRange (which would be really nice)
=> Updated basics.md with rand crate snippets

src/net.md
I know the parsing url and create url from base example have already been implemented, but since I have taken a fairly different approach, I wanted to make this pull request anyway.
If you'd like to have only the example about retrieving the origin of the url let me know.
Resolves #33 #36
Thanks for you time
=> Added parsing url, create url from base and retrieve origin examples

theme/book.css
Added theme/book.css. It is a direct copy of the standard mdbook
book.css file with one addition of `width: 100%;` to the `table` style.
Infortunately mdbook allows only to substitute whole book.css.
Moreover please note that due to https://github.com/azerupi/mdBook/issues/227
`theme` directory has to be placed at the project root instead of `src`
resolves: https://github.com/brson/rust-cookbook/issues/42
=> Make the table width consistent

theme/book.css
Added explicit width values for first and second
table columns corresponding to "Recipe" and "Crates".
Please note that this is a broad CSS style for all tables
which will break any non TOC tables.
For a cleaner solution we would need to explicitly
add class attribute to the generated HTML.
resolves: https://github.com/brson/rust-cookbook/issues/42
=> Make consistent table column widths

src/net.md
resolves: https://github.com/brson/rust-cookbook/issues/37
=> implemented "Remove fragment identifiers and query pairs from a URL"

src/app.md, src/intro.md
r? @dtolnay 
cc https://github.com/brson/rust-cookbook/issues/61
I didn't add the entry for the 'syslog' example because I don't know which crate implements log for the syslog.
=> Add placeholders for log examples

Cargo.toml, src/intro.md, src/net.md
I took the liberty of adding reqwest to cargo.toml and renaming
"Make a HTTP GET request after parsing a URL" to "Make a HTTP GET request"
as reqwest handles basic URL parsing internally and there seamed
no reason to make the example more complex than required.
Also `rust,no_run` skeptic annotation was used to allow for compilation without making actual http requests.
resolves: https://github.com/brson/rust-cookbook/issues/39
blocked by: https://github.com/seanmonstar/reqwest/pull/79
Unfortunately reqwest is still dependent on serde 0.9 which causes our "encoding.md" examples to fail. Until https://github.com/seanmonstar/reqwest/pull/79 is resolved I would be happy to resolve any problems with the PR.
=> Implemented "Make a HTTP GET request" example

CONTRIBUTING.md
Link to the thread: https://internals.rust-lang.org/t/rust-libz-blitz/5184 for libz blitz. See https://github.com/brson/rust-cookbook/issues/63
=> add libz blitz link

CONTRIBUTING.md
[crate-tasks] links to https://github.com/brson/rust-cookbook/issues?q=is%3Aissue+is%3Aopen+label%3Acrate-tasks
It's one other step in order to fix: https://github.com/brson/rust-cookbook/issues/63
(I'm making different PR for each step cause I think it's easier to review, not sure I'm right)
=> add crate-tasks link

src/about.md
The links in the table of contents of this page are broken: https://brson.github.io/rust-cookbook/about.html
This PR is vaguely related to https://github.com/brson/rust-cookbook/issues/63 and https://github.com/brson/rust-cookbook/issues/64
=> fix links in table of contents

Cargo.toml, src/app.md, src/intro.md
Please see https://github.com/brson/rust-cookbook/issues/61
=> Implements "Log to the Unix syslog" example

src/app.md, src/intro.md
This recipe shows how to create a custom logger and log various messages into it. Based on #69 and is a part of #61 
Side note:
Too many errors and mistakes were made in https://github.com/brson/rust-cookbook/pull/69 (and it's now in conflit with commit like "oops", so its quality is poor). Now with the help of @dtolnay and @budziq I re-created a clean (?) PR based on this todo-list https://github.com/brson/rust-cookbook/pull/69#issuecomment-300814527
=> Add "Log messages with a custom logger" recipe

Cargo.toml, src/app.md, src/intro.md
I'm not sure if the explanation is clear enough.
Also grouped the env_logger based examples together
=> Implemented "Enable log levels per module" example

src/intro.md, src/net.md
resolves https://github.com/brson/rust-cookbook/issues/81
=> removed the stubs for "Serialize a `Url`" example

src/about.md
Fixes #59.
I didn't modify the others examples since they didn't already use `error-chain`. Should I?
=> Recommend the use of quick_main.

deploy.sh
"cron" builds will trigger cargo test with all dependency versions
replaced with "*" to check for incompatible dependencies.
Also cron builds will never publish gh-pages
This is somewhat hacky so I am open to suggestions. I guess that I would prefer to remove Cargo.lock altogether and replace dependency versions in Cargo.toml in the repo instead of modifying it on the fly but I see no other possibility to make dependency check only in Travis nightly.
reolves https://github.com/brson/rust-cookbook/issues/89
related to https://github.com/brson/rust-cookbook/issues/75
=> Travis "cron" builds run tests with "*" dependencies

src/intro.md, src/net.md
=> HEAD request

src/basics.md, src/intro.md
This adds an example which calls `git log --oneline` in a subprocess and parses stdout to grab the hash and commit message for all commits in the current repo's history as discussed in #108.
I'm not quite sure which category this example belongs in. About the closes thing would be `filesystem`, but calling a subprocess doesn't really have anything to do with the filesystem...
(fixes #108)
=> Parsing subprocess output

src/basics.md, src/intro.md
change crate name from `lazy-static` to `lazy_static` (woops)
=> fix `lazy_static` links

src/encoding.md, src/intro.md
The example might be a little contrived. I will gladly update it if necessary.
resolves: https://github.com/brson/rust-cookbook/issues/85
=> implemented "Encode a string as application/x-www-form-urlencoded"

src/net.md, theme/book.css
Updated net.md to hide error_chain boilerplate by default
it can be exposed by selecting the "expand button"
The expand button is no longer hidden
This is connected to https://github.com/brson/rust-cookbook/issues/106
@dtolnay please check if net.md and decide if such approach is acceptable
- Please note no other section was updated as this is only a demo for the moment ;)
=> Hide non essential parts of "Network" snippets by default

src/intro.md, src/net.md
=> Added networking example to listen on random socket using tcp/ip

src/app.md, src/basics.md, src/encoding.md, src/net.md
Modified all examples to hide noisy error_chain related code
resolves: https://github.com/brson/rust-cookbook/issues/106
=> Hide error_chain boiler plate by default in all examples

theme/book.css
Inline code with hyperlink has now the same color
and on hover underline as standard hyperlink.
resolves https://github.com/brson/rust-cookbook/issues/142
=> Inline code with hyperlink is now highlighted

src/app.md
s/diretories/directories
in Application Development example Recursively find duplicate file names.
=> Fix typo in ex-dedup-filenames

src/encoding.md, src/intro.md
1. Updated intro.md to include link to the hex encoding / decoding example.
2. Updated text of the hex encoding / decoding badge to display "data-encoding" instead of "url".
Note: The "data-encoding" badge displayed on intro.md is shorter and wider than the other badges. As far as I can tell this is due to the relatively long name of the "data-encoding" crate. If there is some way for me to resolve this please let me know and I will do so.
=> Fix hex encoding / decoding example.

src/app.md
=> Add basic usage of env_logger's error! macro

src/app.md, src/basics.md, src/concurrency.md, src/encoding.md, src/intro.md, src/net.md
The crate version badges are colour-coded such that post-1.0 (which we can loosely interpret as “good”) is blue, and pre-1.0 (“bad”) is orange. Given that colour scheme, all those red category badges make me think something bad is going on. This PR replaces them with light grey ones.
=> Replace red on category badges

src/basics.md, src/intro.md, src/net.md
fixes https://github.com/brson/rust-cookbook/issues/143
Left-out "API, GitHub, Gist TCP/IP, TOML. JSON, Unix, URL, REST, POST. HTTP, GET, "
=> Fixed example capitalization to sentence case

src/basics.md
BufReader is constructed from some type that implements `Read`, not `Write`
=> BufReader is constructed from some type that implements Read, not Write

src/basics.md, src/encoding.md, src/net.md
- Generate random numbers within a range
- Generate random numbers with normal distribution
- Generate random values of a custom type
- Encode a string as application/x-www-form-urlencoded
- Remove fragment identifiers and query pairs from a URL
- Make a HTTP GET request
- Download a file to a temporary directory
Connected with: https://github.com/brson/rust-cookbook/issues/139
=> Removed passive voice from 7 examples

Cargo.toml, src/concurrency.md, src/intro.md
fixes: https://github.com/brson/rust-cookbook/issues/102
Currently the example is marked as "no_run" as it leaves `output.png` in rust-cookbook cwd due to https://github.com/brson/rust-skeptic/issues/23 (there is a PR for it https://github.com/brson/rust-skeptic/pull/26)
Also on weaker machines the example in debug build might take 1-2s and I would not like to make the test even slower.
Also maybe we could add additional thumbnail for the output.png?
=> Added "Draw fractal dispatching work to a thread pool" example

Cargo.toml, LICENSE-APACHE, LICENSE-MIT, README.md
Rust Cookbook is licensed under dual MIT/Apache-2.0 license.
Used boilerplate from [Rust API guidelines](https://github.com/brson/rust-api-guidelines#license) but due to section naming clash of "Contribution" with preexisting "Contributing" I've decided to merge the section with "License" section.
fixes: https://github.com/brson/rust-cookbook/issues/193
=> Added clarification of licensing

src/app.md, src/intro.md
- Added "Compress a directory into tarball" example
- Reworded the example to use Decompress consistently
- removed tempdir
- fixed api links
fixes: https://github.com/brson/rust-cookbook/issues/188
fixes: https://github.com/brson/rust-cookbook/issues/186
cc: https://github.com/brson/rust-cookbook/issues/185
=>  Added "Compress a directory into tarball" example and reworded decompress example

Cargo.toml, src/basics.md, src/intro.md
I've added the bitflags example but unfortunately there is a linking error due to other book dependencies using different bitflags versions.
clap -> bitflags 0.8.2
png -> bitflags 0.7.0
openssl -> bitflags 0.9.1
This results in standard problem
```
error[E0465]: multiple rlib candidates for `bitflags` found
--> /tmp/rust-skeptic.wsSHTSHfCBhF/test.rs:3:1
|
3 | extern crate bitflags;
| ^^^^^^^^^^^^^^^^^^^^^^
...
```
It the moment I have no idea how to work around such problem in general without changes to skeptic or cargo itself
fixes: https://github.com/brson/rust-cookbook/issues/189
fixes: https://github.com/brson/rust-cookbook/issues/114
---
~~Update: `image-png` and `image` have released a new version compatible with bitflags "^0.9". Still waiting for `clap-rs`~~ dependencies updated on …
=> Added "Define and operate on a type represented as a bitfield" example

src/app.md, src/intro.md
fixes #187 
Adds example to decompress tarball by iterating over entries while removing a specified path prefix.
All tests passed locally.
=> Adds example for "Decompress tarball while removing path prefix"

src/app.md, src/intro.md
This is a rough draft of the file loop example. I'd love some feedback on how to make it more concise. Right now there's a lot of boiler plate on iterating through the file system, and check parent paths. Though, the file system boilerplate could help make a better case for walkdir. @budziq , thanks for the tip on how to make a sym link loop. Fixes #207
=> File Loop app example

src/basics.md, src/intro.md
For Issue #244 
A few concerns I have:
- Is it even a good example to only filter by a couple words?
- I used `RegexSetBuilder` instead of `RegexSet`, I think it's a friendlier way to force case insensitive search and shows the builder pattern.
- Is it potentially confusing to use shadowing there with `let line = line?;`
=> Filter a log file by matching multiple regular expressions

CONTRIBUTING.md, README.md, deploy.sh, src/intro.md, src/main.rs, src/net.md, theme/index.hbs
- fixed stargazers example broken due to repo move
- fixed edit functionality broken due to repo move
cc https://github.com/rust-lang-nursery/rust-cookbook/issues/258
=> fixed links and CI auto-deploy after move to rust-lang-nursery

src/concurrency.md, src/intro.md
I initially went with an example like this:
```rust
extern crate rand;
extern crate rayon;
use rand::Rng;
use rayon::prelude::*;
fn main() {
let mut vec = vec![0i64; 1_000_000];
// Generating random numbers to be sorted later
vec.par_iter_mut().for_each(|p| *p = rand::weak_rng().gen::<i64>());
// Using Rayon's Parallel QuickSort to sort the vector
vec.par_sort_unstable();
}
```
but that seemed overly simplistic(I think you are more likely to sort strings than just integers).
Had no idea what to write in the description, under the code...
=> Add rayon parallel sort example

src/encoding.md, src/intro.md
=> Add example: "Filter csv records matching a predicate".

src/SUMMARY.md, src/build_tools.md, src/intro.md, src/links.md
issue #292
@budziq Here's what I've got so far. Were you thinking of a more in-depth build-tools intro? Does the wording make sense?
=> Add build tools section & basic `cc` example

src/basics.md, src/intro.md
For a given <directory>, shows the `<number>` biggest
files/subdirectories and its human readable size.
Equivalant Unix command:
du -ah <directory> | sort -hr | head -n <number>
=> Add "Run piped external commands" example

src/app.md, src/intro.md
=> Add "Parse a complex version string" example

src/app.md
At the risk of bikeshedding, I revised the styling I used for #305 to match the styling used in #308.
Probably not even necessary, though. Feelings will not be hurt if the request is closed :')
(should I have opened an issue before PR'ing?)
=> Match semver crate examples' styling

src/basics.md, src/intro.md
=> add "Sign and verify a message with HMAC digest" example

src/build_tools.md, src/intro.md
I added an example for the compilation and linking of a bundled C++ library (#296).
=> Add c++ linking example

src/app.md, src/intro.md
=> Add "Check external command version for compatibility"

src/encoding.md, src/intro.md
=> Add "read csv records"

src/basics.md, src/intro.md
Adds recipe for #288 
* Slightly changes the wording on the example (explicitly mentioning PBKDF2)
* Uses PBKDF2 key derivation function
* Verifies password with hash
cc #213 
fixes #288
=> Adds recipe for salt and hash a password using ring crate

src/intro.md, src/net.md
This is my first PR in a Rust project, probably not the most idiomatic Rust but I'm here to learn.
=> Add "Make a partial download with HTTP range headers" example #291

src/build_tools.md, src/intro.md
=> Add 'Compile a C library while setting custom defines' (#295)

src/app.md, src/basics.md, src/concurrency.md, src/net.md
=> Update examples with "for_each"

CONTRIBUTING.md
It was not previously clear when a contributor should use `error_chain`
and when they should use `main()`. This patch adds a couple sentences to
the section on error handling to make that more explicit.
=> Updates the wording on error handling to improve clarity in CONTRIBUTING.md

src/basics.md, src/intro.md, src/links.md
=> add "Obtain backtrace of complex error scenarios" example

src/concurrency.md, src/intro.md
=> Adds search unordered items in parallel example

src/basics.md, src/intro.md, src/links.md
I just explored a bit this repo, read the contribution guidelines, one thing lead to another and I added the measure-elapsed-time example.
fixes https://github.com/rust-lang-nursery/rust-cookbook/issues/341
=> Added measure-elapsed-time example

src/concurrency.md, src/intro.md
fixes #329
* Adds example in `concurrency.md`
* Adds links to `intro.md`
=> Adds parallel map-reduce recipe

src/concurrency.md, src/intro.md
fixes https://github.com/rust-lang-nursery/rust-cookbook/issues/331
edit: added `fixes #311` clause to description to close the issue on merge.
=> Add rayon example with any and all

src/basics.md, src/intro.md
=> Add "Redirect both stdout and stderr of child process to the same fle"

src/intro.md
The "Log messages to a custom location" item on the intro page had only
the `log` badge, but was missing the `log4rs` badge. The `log4rs` badge
was already present on the recipe.
```markdown
```
=> Add a missing log4rs badge to intro

src/basics.md, src/intro.md
=> Add example for checked arithmetic of chrono

src/basics.md, src/intro.md
=> Add Datelike and Timelike example

src/basics.md, src/intro.md
fixes #360 and should incorperate all the changes made
=> Adds "converting a local time to UTC time and vice versa" recipe

src/basics.md, src/intro.md
=> issue #361 fixed

src/basics.md, src/intro.md, src/links.md
fixes #339 
Hello @budziq ! Another PR :-) I also added a commit to update the std badge version.
=> Add "Process child process output continuously" example

src/app.md, src/intro.md
=> semver example: find the latest version satsifying given range

src/basics.md, src/intro.md
fixes #287 r? @budziq 
I categorized this example under `text processing`.  Do you think that is the appropriate category?
=> Issue287: create random password from a set of allowed characters

src/basics.md
The example **Replace all occurrences of one text pattern with another pattern** mentions a "British English date pattern" when it's using ISO 8601 dates. Change the explanation and a variable name. Also use the same date in code that's in the explanation Untested, sorry.
fixes #360
=> rephrase text pattern replacement example

src/build_tools.md
This is a trivial fix.
```markdown
```
=> fix C++ linking example

CONTRIBUTING.md
Takes recommendations put forth from @budziq and merge them into CONTRIBUTING.md
Attempts to make the guideline more readable by segmenting it and adding embedded example.
fixes #302
=> Style guide update to include embedded example and sections

.github/PULL_REQUEST_TEMPLATE.md
Removed checkbox for CC0 comments--they are no longer required.
=> Update github pull request template after CC0 licensing change

src/SUMMARY.md, src/algorithms.md, src/algorithms/sorting.md, src/algorithms/sorting/sort.md, src/algorithms/sorting/sort_float.md, src/algorithms/sorting/sort_struct.md
* Add simple sorting vector of integers
* Add sorting of vector of floats
* Add sorting of vector of structs by custom natural order
* Add sorting of vector of structs by custom comparator
fixes #437
=> Recipe Series: Sort Vector #437

Cargo.toml, ci/dictionary.txt, src/SUMMARY.md, src/cli.md, src/cli/ansi_terminal.md, src/cli/ansi_terminal/ansi_term-basic.md, src/cli/arguments.md, src/links.md
fixes #438 
it fixes #438 but The link is not created in the mdbook
=> added ansi_term example

ci/dictionary.txt, src/links.md
Seeing as we are adding a few `ndarray` recipes in #450 it makes sense to add the badge and link.
=> Add ndarray badge and link

src/science/mathematics.md, src/science/mathematics/linear_algebra.md, src/science/mathematics/linear_algebra/add-matrices.md, src/science/mathematics/linear_algebra/multiply-matrices.md, src/science/mathematics/linear_algebra/multiply-scalar-vector-matrix.md
Part of #450 
I'm unsure as to how we want to organise these. #461 seems to use another `linear-algebra` crate, but I'm not sure this is necessary. Could we just put all the recipes in `science/mathematics/matrices.md`?
=> Add various simple matrix recipes

src/science/mathematics/linear_algebra/vector-norm.md
This removes an unnecessary allocation caused by `.mapv()` in the original version, replaces `&Array1<f64>` argument types with `ArrayView1<f64>` (see the new text for reasoning), and takes advantage of the `array!` macro to make the array creation more concise.
=> Improve vector norm recipe

src/science/mathematics/linear_algebra/multiply-scalar-vector-matrix.md
The original version was incorrect about `ndarray`'s treatment of 1-D arrays as vectors, and it incorrectly indicated that `*` performed matrix multiplication.
`ndarray` decides whether a 1-D array is a row vector or column vector in matrix multiplication by whether it is on the left-hand side or right-hand side. (The behavior matches NumPy. If it's on the left-hand side, it's a row vector, while if it's on the right-hand side, it's a column vector.) The original version incorrectly indicated that calling `.reversed_axes()` on a 1-D array would make it into a column vector. In fact, calling `.reversed_axes()` on a 1-D array has no effect since a 1-D array has only 1 axis.
Matrix multiplication is performed with `.dot()`, not `*`. The `*` operator performs element-wise multiplication.
=> Fix multiply-scalar-vector-matrix recipe

src/web/clients.md, src/web/clients/download/post-file.md
Two link targets in the web client download examples have been swapped, revert them. And also remove a dot at the end of a heading in one of the examples.
=> Fix swapped links in web client examples

src/encoding/csv/delimiter.md
The CSV encoding tab delimiter example has a struct to deserialize into.
However it wasn't used.
I've changed it to use the provided struct.
It may make more sense to remove it instead, as it isn't the point of
this example. If it turns out to be the preferred method in the pull
request process, I'll do so.
=> Use provided struct in CSV tab delimiter example

src/encoding/string/percent-encode.md
The source code uses the `url` crate not the `percent-encoding` crate.
This change makes the text consistent with the source code.
=> Correct referenced crate in percent-encode chapter

Cargo.toml, src/database/sqlite/initialization.md
Previous version gave me
```
error[E0282]: type annotations needed
--> src/main.rs:13:9
|
13 |         &[],
|         ^^^ cannot infer type
error: aborting due to previous error
```
on stable and nightly.
=> Fix SQLite example so it compiles

src/database/sqlite/transactions.md
error[E0282]: type annotations needed
--> /tmp/rust-skeptic.RdMBHU9Ab9y6/test.rs:20:42
|
20 |     tx.execute("delete from cat_colors", &[])?;
|                                          ^^^ cannot infer type
error: aborting due to previous error
For more information about this error, try `rustc --explain E0282`.
test transactions_sect_using_transactions_line_15 ... FAILED
=> update to sqlite version syntax

src/web/clients/api/rest-get.md
Try `cargo run --verbose` after copying the code into a separate project. This example snippet does not compile and requires `serde` create to be present in the main.rs. So including the serde crate will fix the compilation error.
```markdown
```
=> Fix the compilation error

Cargo.toml, src/concurrency/thread/threadpool-walk.md, src/cryptography/hashing/hmac.md
fixes issue #573 
Questions/concerns:
Section does not pass test under cargo test, but runs fine locally, on Rust playground, and under 'mdbook serve' on localhost.  It appears testing may refer to an older version of the ring crate.  Which version of ring does 'cargo test' call?
=> Fix issue #573 - hmac example

src/science/mathematics.md
=> Typo: 'marix' => 'matrix'

Cargo.toml
fixes the test case **'insert_select_sect_insert_and_select_data_line_8'** which is causing CI to fail.
```
error[E0282]: type annotations needed for `rusqlite::MappedRows<'_, [closure@C:\Users\LONELY~1\AppData\Local\Temp\rust-skeptic.QY792HCVQQOx\test.rs:41:42: 46:6]>`
--> C:\Users\LONELY~1\AppData\Local\Temp\rust-skeptic.QY792HCVQQOx\test.rs:42:9
|
41 |     let cats = stmt.query_map(NO_PARAMS, |row| {
|         ---- consider giving `cats` the explicit type `rusqlite::MappedRows<'_, [closure@C:\Users\LONELY~1\AppData\Local\Temp\rust-skeptic.QY792HCVQQOx\test.rs:41:42: 46:6]>`, where the type parameter `E` is specified
42 |         Ok(Cat {
|         ^^ cannot infer type for type parameter `E` declared on the enum `Result`
error: aborting due to previous error
For more information about …
```
=> bump up 'rusqlite' to fix failing test

src/database/postgres/insert_query_data.md
fixes #488 
Test code causing the issue was for **postgres**, not **sqLite**
=> Fix dead code issue from #488

src/science/mathematics.md
fixes broken links in : [https://rust-lang-nursery.github.io/rust-cookbook/science/mathematics.html](https://rust-lang-nursery.github.io/rust-cookbook/science/mathematics.html)
When going to a recipe from there:
https://rust-lang-nursery.github.io/rust-cookbook/science/science/mathematics/linear_algebra.html#vector-norm
https://rust-lang-nursery.github.io/rust-cookbook/science/mathematics/linear_algebra.html#vector-norm
=> fix links in science/mathematics.md

src/science/mathematics/miscellaneous/big-integers.md
Used the factorial example as a reference in a Stack Overflow [answer] yesterday. Thought I'd just quickly update it to use an inclusive range instead.
[answer]: https://stackoverflow.com/a/65561835/2470818
=> Changed to use inclusive range

src/SUMMARY.md, src/web.md, src/web/clients/authentication.md, src/web/clients/authentication/basic.md
Part of #436 
Perform a basic HTTP authentication with `reqwest`'s blocking client.
If you'd prefer to use an asynchronous client instead, just say the word. (Personally, I don't have a strong preference for the sake of this example in either direction. But ultimately opted to go with the synchronous client to minimize the complexity of this example and purely focus it on the authentication aspect.)
=> demonstrate basic http authentication

src/encoding/csv/delimiter.md
The use of tabs for indentation made the example error due to finding more
columns on the indented lines than intended. Use escaped newlines and line
continuations to prevent the indentation from being part of the records.
=> Use spaces for CSV in indentation

src/algorithms/sorting/sort_struct.md
=> Reduce calling of `to_string()`

src/encoding/string/percent-encode.md
=> Fix percent-encoding link

src/science/mathematics/trigonometry/side-length.md
A triangle with a right angle (1.57 radians) and an angle of 2 radians cannot exist and is physically impossible.
=> Corrected impossible example in side-length.md

Cargo.toml, src/database/sqlite/initialization.md, src/database/sqlite/insert_select.md, src/database/sqlite/transactions.md
`NO_PARAMS` has been deprecated.
For homogeneous parameters, `[value1, value2, ...]` can be used
directly.
For heterogeneous parameters, `params![value1, value2, ...]` is
preferred.
```markdown
```
=> Upgrade rusqlite

src/web.md, src/web/clients.md, src/web/clients/requests.md, src/web/clients/requests/header.md
I've made a few changed to the original recipe:
- made the usage of `error_chain` visible to account for #563 
- switch to the synchronous reqwest client to simplify the recipe
- removed the authorization header since this is now handled via [reqwest::RequestBuilder::bearer_auth](https://docs.rs/reqwest/0.10.6/reqwest/blocking/struct.RequestBuilder.html#method.bearer_auth)
- got rid of the `hyper::header!` macro
- gave the `X-Powered-By` header a more generic/sterile value
- added missing links
fixes #596
=> 596 headers

README.md, ci/install_deps.sh
When Trying to run jamesgraves/rust-cookbook with rust 1.82 as recommended using 0.4.15 the thread paniced.
```markdown
```
=> mdbook 4.43 for rust 1.82

src/concurrency/thread/crossbeam-spsc.md
Currently, it results in linking to
https://rust-lang-nursery.github.io/rust-cookbook/concurrency/concurrency/threads.html
which is a 404.
=> Fix internal link in concurrency/thread/crossbeam-spsc.md

src/links.md
The badge of the ansi_term package is pointing incorrectly to the base64 crate, this is causing that the ansi_term package shows a non existent version
=> fix incorrect badge link

src/concurrency/parallel/rayon-parallel-sort.md
This fixes one breaking skeptic test due to a change in the type of `Alphanumeric` between rand 0.7 and rand 0.8.
=> Convert u8 to char (necessary since rand 0.8)

src/web/clients/api/rest-get.md
Fixed runtime decoding error occurring due to 403 responses from `gh api` because of missing user-agent header
fixes #662 
Feel free to close if you still prefer to use `reqwest::get` for the example but with a different api that doesn't require `user-agent-header`. I'm currently unaware of how to pass headers along with `reqwest::get` and thus used a `reqwest client` in the fix
=> querying-the-web-api examples don't work due to missing user-agent-headers

src/concurrency/thread/threadpool-fractal.md
It is not compiling because of:
`?` couldn't convert the error to `Error`
--> src/main.rs:90:35
|
67  | fn main() -> Result<()> {
|              ---------- expected `Error` because of this
...
90  |     let _ = img.save("output.png")?;
|                                   ^ the trait `From<ImageError>` is not implemented for `Error`
=> Added ImageError handler to error_chain! macro.

src/compression/tar/tar-compress.md
- Call finish to finalize the archive [recommended by tar](https://docs.rs/tar/0.4.41/tar/struct.Builder.html#method.append_dir_all).
- Show an example of adding an archive **without** renaming it.
- Callout differences between `tar::Builder` defaults and `tar(1)` defaults
On seeing these docs I was unsure if there was another, better way, to add all the contents of one directory into an archive. After researching, I see people use this function by call it with an empty string. I feel this is a common operation and would like to see it spelled out in the documentation.
In addition, I hit an edge case where `tar(1)` produced significantly smaller files than the `tar` crate, reproduction: https://github.com/schneems/tar_comparison/blob/bfd420a012b46e80435cf4e7c67ca1661357fde3/README.md. It …
=> Update tar-compress docs

src/web/clients/requests/get.md
Added error to Result for main, otherwise it won't compile. If tokio isn't added with features = ["full"] main won't work, so I thought it would be a good idea to remind them.
```markdown
```
=> Add Error to Result added note for tokio

src/science.md
fixes #634
Replace #include science/mathematics.md from science.md with the correct links from the root folder.
The same rule is already applied to the web/client section, so it is nothing new.
=> fix for science.md links to mathematics chapter

src/development_tools.md, src/development_tools/debugging.md
fixes #671
Same issue as in #634, links in md files included in md files from other folders will have wrong relative path in one of the two locations. in this case the root file development_tools.md was working and the debugging.md was broken.
=> fixes #671 - Development_tools/debugging relative links

src/links.md
Previous badge url display version numbers associated with `rand` crate which do not map to `rand_distr` versions. 
Current: https://badge-cache.kominick.com/crates/v/rand.svg?label=rand_distr
Proposed: https://badge-cache.kominick.com/crates/v/rand_distr.svg?label=rand_distr
=> chore: update `rand_distr` badge url

src/net/server/listen-unused.md
Uses ToSocketAddrs' trait to have any of IPv4 or IPv6 as supported by the OS, or even DNS names.
=> net/server/listen-unused: simpler and with IPv6 support.

Cargo.toml, src/about.md, src/development_tools/build_tools/cc-bundled-static.md, src/errors.md, src/errors/handle.md, src/errors/handle/main.md, src/links.md
After reviewing the state of error handling in rust, it would seem the deprecated `error-chain` has been superseeded on blessed.rs with anyhow and thiserror.  This updates the cookbook to adopt this error strategy
=> replacing error handlers

book.toml
fixes #678
fixed?
I don't know if there's a reason why this hasn't been added yet?
=> fixes #678 Added Edit/Github Icon

.cargo/config.toml, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md, ci/dictionary.txt, src/database/postgres/aggregate_data.md, src/web/clients.md, xtask/Cargo.toml, xtask/README.md, xtask/src/main.rs, xtask/src/mdbook.rs, xtask/src/tests.rs
fixes #715 fixes #712 
- reworked book operations in xtask
- updated readme for new build command
- updated contribution.md for new test commands
- fixed missing dictionary
- added contributor tests to xtask (`cargo test`, `mdbook serve -o`, `./ci/spellcheck.sh`, `link-checker ./book` (moved to [Lychee](https://github.com/lycheeverse/lychee)))
- fixed broken link
created xtask single bin and alias instead of a workspace to prevent breaking ci or other stuff
does this fix #712 ?  
are the changes form #715 fine?
=> added xtask bin for tests (#715, #712)

src/database/sqlite/initialization.md, src/database/sqlite/insert_select.md, src/database/sqlite/transactions.md
fixes #691 
makes sure the warnings are all handled by accessing and showing proper if let Result yielding.
```markdown
```
=> issue-689 updated rusqlite to use () for no params

src/about.md
The error handling link to the Rust Book on the About page was broken. I replaced it with the one I assumed was correct.
```markdown
```
=> Fix error handling link in about page
