rust-lang-nursery/rust-cookbook

- CONTRIBUTING.md
- README.md
- pages/byteorder.md
Add skeleton for contribution guide and fix badge for Byteorder
> Contributing

- README.md
Add links to work in progress pages
> Add page links

- Cargo.toml
- build.rs
Removes an unneeded & conversion
🍂 🍐
> build.rs runs all the tests with new skeptic library

- Cargo.lock
- README.md
- pages/toml.md
> first examples on toml page

- pages/toml.md
> adding badge to toml page

- Cargo.lock
- Cargo.toml
- src/net.md
> Add url joining example

- src/net.md
> Add example for creating base url by clearing path

- src/app.md
- src/concurrency.md
- src/encoding.md
- src/intro.md
- src/net.md
resolves: https://github.com/brson/rust-cookbook/issues/56
> Made TOC's and badges consistent between chapters

- CONTRIBUTING.md
Third step of https://github.com/brson/rust-cookbook/issues/63
> Fix ["how to read this book"] link

- src/app.md
- src/intro.md
resolves https://github.com/brson/rust-cookbook/issues/71
> Fixed incorrect badges in app.md and intro.md

- CONTRIBUTING.md
Should resolve rest of the problems from: https://github.com/brson/rust-cookbook/issues/63
> Fixing rest of broken links in CONTRIBUTING.md

- CONTRIBUTING.md
- README.md
- src/basics.md
- src/intro.md
- src/net.md
> Fixed typos

- src/basics.md
- src/intro.md
I do not know if rand examples are still open for contribution.
But I have added two more basic examples:
- "Generate random numbers within a range"
- "Generate random numbers with normal distribution"
These seam to be relatively frequently asked on SO.
> Added two more rand examples

- src/intro.md
- src/net.md
Implemented one of the examples "Download a file to a temporary directory" mentioned on https://github.com/brson/rust-cookbook/issues/24#issue-213203617
> Implemented "Download a file to a temporary directory" example

- src/intro.md
- src/net.md
As mentioned in tracking issue https://github.com/brson/rust-cookbook/issues/24
"Query the GitHub API"
"Create and delete Gist with GitHub API"
> Implemented two examples for "Query the GitHub API"

- theme/index.hbs
I have added an edit button to the page template allowing for direct edit of given page in GitHub
Unfortunately I see no other way than pulling whole default mdbook index.hbs and editing it inline.
At least it was possible to avoid pulling the book.js also...
This should resolve: https://github.com/brson/rust-cookbook/issues/82 but please note that it is my first time editing javascript so the solution might not be ideal.
> Added Edit button

- Cargo.toml
- src/basics.md
- src/intro.md
> Add lazy_static example

- src/basics.md
- src/intro.md
> Add global mutable state example

- Cargo.toml
- src/app.md
- src/intro.md
> Add 'Recursively find duplicate file names' example

- src/app.md
This is for https://github.com/brson/rust-cookbook/issues/97
> Include logs to a custom location

- src/app.md
- src/intro.md
This is to solve #125 
Happy to tweak this with any reviews, comments and ideas :smiley:
> Add file-predicate example

- src/intro.md
- src/net.md
> Network example: Post a file to paste-rs

- src/intro.md
- src/net.md
> Include Paginated API example

- src/app.md
> Basic usage of `env_logger` + debug!

- src/about.md
fixes https://github.com/brson/rust-cookbook/issues/153
> Described expand button in snippets

- src/about.md
- src/app.md
- src/basics.md
- src/encoding.md
- src/logging.md
- src/net.md
- run rustfmt on all snippets
- adjusted indentation on hidden error boilerplate
- removed some trailing whitespace
- added error boilerplate hiding to "Consume a paginated RESTful API" example
fixes https://github.com/brson/rust-cookbook/issues/158
> Corrected snippets formatting

- src/concurrency.md
- src/intro.md
> Add crossbeam::spawn example

- src/logging.md
- src/net.md
- Query the GitHub API
- Create and delete Gist with GitHub API
- Enable log levels per module
- Log to the Unix syslog
connected to: https://github.com/brson/rust-cookbook/issues/139
> Removed passive voice from 4 examples

- src/basics.md
- src/encoding.md
- src/logging.md
- Run an External Command and Process Stdout
- Encode and decode base64
- Log messages with a custom logger
- Log messages to a custom location
fixes https://github.com/brson/rust-cookbook/issues/139
> Removed passive voice from the last 4 examples

- src/about.md
Here's some content for the about page. Fixes https://github.com/brson/rust-cookbook/issues/64
r? @dtolnay
> Write about.html

- src/net.md
fixes https://github.com/brson/rust-cookbook/issues/172
> Fixed "Consume a paginated RESTful API" example to reuse reqwest::Client

- src/intro.md
- src/net.md
fixes https://github.com/brson/rust-cookbook/issues/91
> "Set custom headers and URL parameters for a REST request" example

- Cargo.toml
- src/basics.md
- src/intro.md
I'm keen to help with the cookbook more.
> Add memmap example for random file access

- src/net.md
Also sorted the reference links section in net.md
fixes https://github.com/brson/rust-cookbook/issues/94
> Added short mention about OAuth authorization

- src/app.md
- src/intro.md
Example how to iterate files in directory
to a given depth and accumulate their sizes.
[issue#179](https://github.com/brson/rust-cookbook/issues/179)
> Add walkdir example

- .travis.yml
due to upcoming breaking release of mdbook that would
silently break styling of rust-cookbook
> Pinned mdbook version to 0.0.22

- Cargo.toml
- src/basics.md
Also fixed two examples that depended on execution PWD in project root.
fixes https://github.com/brson/rust-cookbook/issues/194
> Moved to skeptic 0.10

- Cargo.toml
- src/intro.md
- src/net.md
> "Extract all links from a webpage" example

- src/app.md
> update "recursively find all files with given predicate" to use follow_links

- src/intro.md
- src/logging.md
> Adds example for "Logging to stdout instead of stderr"

- src/app.md
- src/intro.md
- src/logging.md
> Use a custom environment variable to set up logging

- .travis.yml
- deploy.sh
- src/encoding.md
- src/net.md
fixes https://github.com/rust-lang-nursery/rust-cookbook/issues/238
> Added OSX CI and cleaned warnings on nightly

- src/app.md
- src/intro.md
> Added "Check if given version is pre-release" example.

- src/encoding.md
- src/intro.md
also removed some unneeded "Debug" derives
> Reorganized the csv examples for more logical flow

- src/basics.md
- src/intro.md
- src/links.md
Checking in to see if I remembered everything that should be included in a new example.
* Add link to date-and-time-badge at badge-cache.kominick.com
* Add link to date-and-time category at crates.io
* Add all necessary document structure related to the aformentioned
See also: #324
> Add example for formatting chrono::DateTime

- src/basics.md
- src/concurrency.md
- src/encoding.md
- src/intro.md
> Corrected typos

- src/logging.md
Same issue as #353, another missed spot
@budziq noticed - thanks :)
> Add missing log4s badge at top of Logging.md

- README.md
> Added local mdbook instructions to README.md

- src/basics.md
- src/intro.md
- src/links.md
* Update std badge version
* Remove duplicate ex-format-datetime
fixes #399
> Added file names modified in the last 24 hours in CWD

- src/basics.md
- src/encoding.md
- src/logging.md
- src/net.md
> Fix broken links

- src/basics.md
- src/links.md
> Update doc link location for ring crate

- src/basics.md
> Fix broken rand links

- theme/index.hbs
> Update template to support FontAwesome move

- src/links.md
- src/science.md
- src/science/mathematics.md
- src/science/mathematics/latitude-longitude.md
* Added recipe: Distance between two points on the Earth
* Update std badge version
fixes: #446
> Recipe: Distance between points

- src/science.md
- src/science/mathematics/linear-algebra/vector_norm.md
Part of tracking issue #450.
Once #452 is merged I will rebase and add appropriate section links.
Similarly, once #463 is merged I will update badge links.
> Adds vector norm example.

- src/compression/tar/tar-compress.md
- src/compression/tar/tar-decompress.md
- src/compression/tar/tar-strip-prefix.md
> Removes quick run in favor of main for compression recipes.

- ci/install_deps.sh
> Python 3.6 not installed by default

- src/algorithms/sorting/sort_struct.md
> Fix little typo

- ci/dictionary.txt
- src/SUMMARY.md
- src/text.md
- src/text/string_parsing.md
- src/text/string_parsing/from_str.md
> Implement the FromStr trait for a custom struct

- Cargo.toml
- ci/dictionary.txt
- src/links.md
- src/science/mathematics.md
- src/science/mathematics/linear_algebra.md
- src/science/mathematics/linear_algebra/invert-matrix.md
- src/science/mathematics/statistics.md
> added invert-matrix to /science/mathematics/linear_algebra

- src/database.md
- src/database/postgres.md
- src/database/postgres/aggregate_data.md
> added data aggregation example for postgres

- Cargo.toml
- ci/dictionary.txt
- src/links.md
- src/text.md
- src/text/string_parsing.md
- src/text/string_parsing/graphemes.md
Hey @branderson, would you mind taking a look at this? `cargo test` seems fine but I can't get the `mdbook` test to run locally (only the one test I'm adding).
> add unicode_segmentation example

- src/database/postgres/create_tables.md
- src/database/postgres/insert_query_data.md
- src/mathematics/statistics.md
- src/science/mathematics.md
> fixed broken links

- src/database/sqlite/initialization.md
- src/database/sqlite/insert_select.md
I researched the Chrono library and made sure the code would compile with the latest Rust 2018 setup.
```markdown
```
> Old Code Would Not Compile

- src/concurrency/thread/threadpool-walk.md
- src/cryptography/encryption/pbkdf2.md
- src/cryptography/hashing/hmac.md
- src/datetime/parse/string.md
- src/development_tools/debugging/log/log-custom-logger.md
- src/development_tools/debugging/log/log-syslog.md
- src/development_tools/versioning/semver-complex.md
- src/development_tools/versioning/semver-increment.md
- src/development_tools/versioning/semver-prerelease.md
- src/encoding/complex/endian-byte.md
- src/encoding/complex/json.md
- src/encoding/complex/toml.md
- src/encoding/csv/delimiter.md
- src/encoding/csv/invalid.md
- src/encoding/csv/read.md
- src/encoding/string/hex.md
- src/encoding/string/percent-encode.md
- src/file/read-write/memmap.md
- src/file/read-write/read-file.md
- src/file/read-write/same-file.md
- src/net/server/listen-unused.md
- src/os/external/continuous.md
- src/os/external/error-file.md
- src/web/clients/api/paginated.md
- src/web/clients/api/rest-get.md
- src/web/clients/api/rest-head.md
- src/web/url/fragment.md
- src/web/url/new.md
- src/web/url/origin.md
- src/web/url/parse.md
fixes #506 
removed error-chain from 'Calculate SHA1 sum of iso files concurrently'
> removed error-chain from examples having only one error variant

- src/concurrency/thread/crossbeam-spawn.md
> optimize variable: min -> max

- .gitignore
- src/algorithms/randomness/rand-custom.md
- src/algorithms/randomness/rand-dist.md
- src/algorithms/randomness/rand-passwd.md
- src/algorithms/randomness/rand-range.md
- src/concurrency/parallel/rayon-parallel-sort.md
- src/encoding/string/percent-encode.md
> Exclude percent encoding from skeptic

- src/cryptography/encryption/pbkdf2.md
fixes #529 by:
1. Using `NonZeroU32` instead of `u32` (unfortunately I had to replace the `const`)
2. Using the correct Algorithm.
> Fixes PBKDF2 example

- ci/dictionary.txt
> crate names aren't always proper words

- .travis.yml
- Cargo.toml
- src/algorithms/randomness/rand-custom.md
- src/algorithms/randomness/rand-dist.md
- src/algorithms/randomness/rand-passwd.md
- src/algorithms/randomness/rand-range.md
- src/concurrency/parallel/rayon-parallel-sort.md
- src/concurrency/parallel/rayon-thumbnails.md
- src/cryptography/encryption/pbkdf2.md
- src/development_tools/build_tools/cc-bundled-static.md
- src/encoding/string/percent-encode.md
- src/file/dir/ignore-case.md
- src/web/clients/api/rate-limited.md
- src/web/clients/requests/header.md
- src/web/scraping/broken.md
Changes to skeptic can be seen on https://github.com/andygauge/rust-skeptic
reintroduce tests that had been filtered out
bump glob to 0.3
fixes #590 
fixes #542
> test fixes

- src/cli/ansi_terminal/ansi_term-basic.md
> fix link in ANSI terminal

- src/web/clients/api/rest-head.md
> Fix tiny typo

- Cargo.toml
- src/science/mathematics/linear_algebra.md
- src/science/mathematics/linear_algebra/deserialize-matrix.md
Demonstrate how to serialize and deserialize a large matrix. This is the last remaining item in the matrix series #450 
fixes #450
> (de)-serialize a matrix

- src/os.md
- src/os/external.md
- src/os/external/read-env-variable.md
> read environment variable

- src/web/clients/requests/get.md
> requests: fix link for tokio::main

- src/science/mathematics/statistics/central-tendency.md
- Fixed the missing backticks, as otherwise the links weren't rendered as links. 
- Fixed a few beta links to use stable instead
> Fixed links

- src/web/clients/download/partial.md
> typo exmple -> example

- src/web/clients/api/rest-get.md
fixes typo: reqwet -> reqwest.
> fixes rest-get reqwest typo

- src/data_structures/bitfield.md
> Fix the page header for bitfields

- Cargo.toml
The blocking issue was resolved upstream @djc thank you for helping with skeptic
```markdown
```
> point back to skeptic

- src/compression/tar/tar-strip-prefix.md
> Fix 3.1 with correct `Result`

- src/links.md
- src/web.md
- src/web/clients.md
- src/web/clients/download/basic.md
This PR fixes an incorrect crate depending on
> fix(deps): 'tempdir' -> 'tempfile'
